environment: "local"
createIngress: true

postgres:
  enabled: false
  persistence:
    size: 1Gi
  env:
    POSTGRES_DB: "local-audit-service-db"
    POSTGRES_HOST: 'postgres-14-alpine'
    POSTGRES_PASSWORD: "root"
    POSTGRES_PORT: 5432
    POSTGRES_USER: "root"

net:
  host: "api.cwb03.test"

env:
  ALLOWED_ORIGINS: "http://localhost:4200, http://localhost:4201, http://agency.cwb03.test, http://public.cwb03.test, http://employer.cwb03.test"
  CERBOS_URI: "127.0.0.1:3592"
  DB_CONNECTION_URL: "jdbc:postgresql://audit-service-postgres:5432/local-audit-service-db"
  DB_USERNAME: "root"
  DB_PASSWORD: "root"
  GCP_PROJECT_ID: "cwb03-dev-a1fe"
  SELF_SIGN_PUBLIC_KEY: "${sm://projects/cwb03-dev-a1fe/secrets/cwb03-self-signed-token-public-key/versions/latest}"
  SELF_SIGN_PRIVATE_KEY: "${sm://projects/cwb03-dev-a1fe/secrets/cwb03-self-signed-token-private-key/versions/latest}"
  ENABLE_PUB_SUB: false
  PUB_SUB_TOPIC: topic-audit-events
  PUB_SUB_TOPIC_SUBSCRIPTION: sub-audit-events
  TOKEN_PRIVATE_KEY_SECRET: "cwb03-self-signed-token-private-key"
  TOKEN_ISSUER: "cwb03"
  TOKEN_PRIVATE_KEY_VERSION: "latest"
  # cwb03-events publisher topics separated by comma
  PUBLISHER_TOPICS: projects/cwb03-dev-a1fe/topics/APPLICATION_ROLE_REPORTING,projects/cwb03-dev-a1fe/topics/AUDIT_EVENTS_RECORDING
