environment: "prod"
serviceAccountName: cwb03-sa
createIngress: false

net:
  host: "api.cwb03.dsgov.demo.nuvalence.io"

env:
  ALLOWED_ORIGINS: "http://localhost:4200, http://localhost:4201, https://api.cwb03.dsgov.demo.nuvalence.io, https://agency.cwb03.dsgov.demo.nuvalence.io, https://public.cwb03.dsgov.demo.nuvalence.io, https://employer.cwb03.dsgov.demo.nuvalence.io"
  CERBOS_URI: "127.0.0.1:3592"
  DB_CONNECTION_URL: "jdbc:postgresql://127.0.0.1:5432/cwb03-prod-audit-service-db"
  DB_USERNAME: "${sm://projects/cwb03-prod/secrets/cwb03-prod-db-user/versions/latest}"
  DB_PASSWORD: "${sm://projects/cwb03-prod/secrets/cwb03-prod-db-pass/versions/latest}"
  GCP_PROJECT_ID: "cwb03-prod"
  SELF_SIGN_PUBLIC_KEY: "${sm://projects/cwb03-prod/secrets/cwb03-self-signed-token-public-key/versions/latest}"
  SELF_SIGN_PRIVATE_KEY: "${sm://projects/cwb03-prod/secrets/cwb03-self-signed-token-private-key/versions/latest}"
  ENABLE_PUB_SUB: "true"
  PUB_SUB_TOPIC: "AUDIT_EVENTS"
  PUB_SUB_TOPIC_SUBSCRIPTION: "AUDIT_EVENTS_SUBSCRIPTION"
  TOKEN_PRIVATE_KEY_SECRET: "cwb03-self-signed-token-private-key"
  TOKEN_ISSUER: "cwb03"
  TOKEN_PRIVATE_KEY_VERSION: "latest"
  OTEL_SAMPLER_PROBABILITY: 1.0 # valid values: [0.0 - 1.0]
  # cwb03-events publisher topics separated by comma
  PUBLISHER_TOPICS: projects/cwb03-prod/topics/APPLICATION_ROLE_REPORTING,projects/cwb03-prod/topics/AUDIT_EVENTS_RECORDING
